version: '3.8'

services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: mypass
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: mpotify
#    depends_on:
#      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env    # 👈 Loads environment variables from .env file
#    restart: on-failure
#
#  volumes:
#    mysql_data:

